# Generated by Django 3.1 on 2020-09-08 08:42

from django.db import migrations, models
import django.db.models.deletion
import store.classes


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('variety_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.variety')),
            ],
            bases=(store.classes.CartObject, 'store.variety'),
        ),
        migrations.CreateModel(
            name='ClientReadyToCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField()),
                ('block', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageToClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MinimumCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='admincode',
            options={'verbose_name': 'Admin code lockers', 'verbose_name_plural': 'admin code lockers'},
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Adresse enregistrée', 'verbose_name_plural': 'Adresses enregistrées'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie de produit', 'verbose_name_plural': 'Catégories de produit'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clienttype',
            options={'verbose_name': 'Type de clientèle', 'verbose_name_plural': 'Types de clientèle'},
        ),
        migrations.AlterModelOptions(
            name='collectlocation',
            options={'verbose_name': 'lieu de collecte', 'verbose_name_plural': 'Lieux de collecte'},
        ),
        migrations.AlterModelOptions(
            name='commandstatus',
            options={'verbose_name': 'Statut commande', 'verbose_name_plural': 'Statuts commande'},
        ),
        migrations.AlterModelOptions(
            name='commandtype',
            options={'verbose_name': 'Type de commande', 'verbose_name_plural': 'Types de commande'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Jour', 'verbose_name_plural': 'Jours'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='directwithdrawal',
            options={'verbose_name': 'Emplacement de retrait en direct', 'verbose_name_plural': 'Emplacements de retrait en direct'},
        ),
        migrations.AlterModelOptions(
            name='historic',
            options={'verbose_name': 'Historique commande', 'verbose_name_plural': 'Historique commande'},
        ),
        migrations.AlterModelOptions(
            name='locker',
            options={'verbose_name': 'Casier click&collect', 'verbose_name_plural': 'Casiers click&collect'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Détail de commande', 'verbose_name_plural': 'Détails de commande'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Plage horaire', 'verbose_name_plural': 'Plages horaires'},
        ),
        migrations.AlterModelOptions(
            name='unity',
            options={'verbose_name': 'Unité', 'verbose_name_plural': 'Unités'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Variété produit', 'verbose_name_plural': 'Variétés produit'},
        ),
        migrations.AlterField(
            model_name='collectlocation',
            name='fk_command_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 'withdrawal'), ('type', 'locker'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='store.commandtype'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='instruction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='directwithdrawal',
            name='fk_collect_location',
            field=models.ForeignKey(limit_choices_to={'fk_command_type': 1}, on_delete=django.db.models.deletion.CASCADE, to='store.collectlocation'),
        ),
        migrations.AlterField(
            model_name='directwithdrawal',
            name='fk_time_slot',
            field=models.ForeignKey(limit_choices_to={'fk_command_type': 1}, on_delete=django.db.models.deletion.CASCADE, to='store.timeslot'),
        ),
        migrations.AlterField(
            model_name='locker',
            name='fk_collect_location',
            field=models.ForeignKey(limit_choices_to={'fk_command_type': 2}, on_delete=django.db.models.deletion.CASCADE, to='store.collectlocation'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='fk_command_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('type', 'withdrawal'), ('type', 'delivery'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='store.commandtype'),
        ),
        migrations.AlterField(
            model_name='variety',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='locker',
            constraint=models.UniqueConstraint(fields=('number', 'fk_collect_location'), name='unicque_locker_location'),
        ),
        migrations.AddField(
            model_name='clientreadytocommand',
            name='fk_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.client'),
        ),
    ]
