# Generated by Django 3.1 on 2020-08-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200824_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttype',
            name='available',
        ),
        migrations.RemoveField(
            model_name='commandtype',
            name='available',
        ),
    ]
