# Generated by Django 3.1 on 2020-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200908_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
