# Generated by Django 3.1 on 2020-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200824_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttype',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commandtype',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
