# Generated by Django 3.1 on 2020-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200914_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='image',
            field=models.ImageField(upload_to='medias_variety/'),
        ),
    ]
