# Generated by Django 3.1 on 2020-09-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200916_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistoric',
            name='date_cancellation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistoric',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
