language: python
python: "3.6"      # current default Python on Travis CI
# command to install dependencies
install: pip install -r requirements.txt


services : postgresql

env:
  jobs:
    - DJANGO_SETTINGS_MODULE=marche_en_ligne.settings.travis
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest

# command to run tests
script: ./manage.py test store
